version: '3'

services:
  web:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "8000:80"

  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - app
    command: postgres:5432

  postgres:
    build: ./postgres
    container_name: postgres
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  app:
    build: ./flask
    container_name: flask
    volumes:
      - ./flask/app:/app
    environment:
      FLASK_ENV: 'development'
      FLASK_APP: 'run.py'
    expose:
      - "5000"

